# Generated by Django 4.1 on 2022-09-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montyback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='mode',
            field=models.IntegerField(default=0),
        ),
    ]
