# Generated by Django 4.1 on 2022-09-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montyback', '0003_rename_count_stats_icount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='avg',
        ),
    ]
