# Generated by Django 4.1 on 2022-09-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montyback', '0004_remove_stats_avg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveScore',
        ),
    ]
